# Generated by Django 5.2.13 on 2026-04-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_rename_hub_msgreac_message_idx_hub_message_message_5ea540_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('icon_emoji', models.CharField(blank=True, default='', max_length=16)),
                ('icon_image', models.CharField(blank=True, default='', max_length=500)),
                ('icon_text', models.CharField(blank=True, default='', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profiles', to='hub.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
