# Generated by Django 5.2.13 on 2026-04-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_add_message_edited_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('machine', models.CharField(db_index=True, max_length=200)),
                ('yaml_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_agents', to='hub.workspace')),
            ],
            options={
                'ordering': ['machine', 'name'],
                'indexes': [models.Index(fields=['workspace', 'machine'], name='hub_contain_workspa_74d906_idx'), models.Index(fields=['status'], name='hub_contain_status_3fe062_idx')],
            },
        ),
    ]
