# Generated by Django 5.2.13 on 2026-04-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_containeragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('group', 'Group'), ('dm', 'Direct Message')], db_index=True, default='group', max_length=8),
        ),
        migrations.CreateModel(
            name='DMParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_type', models.CharField(choices=[('agent', 'Agent'), ('human', 'Human')], max_length=8)),
                ('identity_name', models.CharField(db_index=True, max_length=150)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_participants', to='hub.channel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_memberships', to='hub.workspacemember')),
            ],
            options={
                'indexes': [models.Index(fields=['identity_name', 'channel'], name='hub_dmparti_identit_c3b388_idx'), models.Index(fields=['member'], name='hub_dmparti_member__0eac96_idx')],
                'unique_together': {('channel', 'member')},
            },
        ),
    ]
