# Generated by Django 5.2.7 on 2026-04-18 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0020_channelpreference_sort_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_image",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("icon_emoji", models.CharField(blank=True, default="", max_length=16)),
                ("icon_text", models.CharField(blank=True, default="", max_length=16)),
                ("color", models.CharField(blank=True, default="", max_length=16)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
