# Generated by Django 5.2.13 on 2026-04-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_agentprofile_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmembership',
            name='permission',
            field=models.CharField(choices=[('read-write', 'Read & Write'), ('read-only', 'Read Only'), ('write-only', 'Write Only')], default='read-write', max_length=12),
        ),
    ]
