"""CLI commands: serve, vapid-generate.

Phase 1d Step C (plan PR #337): the ``server`` noun group now hosts
``start`` (= former ``serve``), ``status`` (= former ``show-status``)
and ``deploy`` (= former flat ``deploy`` group). The flat legacy verbs
are stubbed in ``_main.py``.
"""
# ruff: noqa: E402
# (E402 ignored file-wide so the bottom-of-file verb registrations can
# import from sibling modules without the isort-style reordering that
# breaks the click.Group → add_command invariant.)

from __future__ import annotations

import json

import click

from scitex_orochi._cli._help_availability import annotate_help_with_availability
from scitex_orochi._cli._helpers import EXAMPLES_HEADER


# ── Phase 1d Step C: noun dispatcher with migrated verbs ───────────────
@click.group(
    "server",
    short_help="Hub server lifecycle",
    help="Hub server lifecycle (start, status, deploy).",
)
def server() -> None:
    """Server-scoped verbs (Phase 1d Step C)."""


# Verbs registered at bottom of file after their definitions.


# ── serve ───────────────────────────────────────────────────────
@click.command(
    epilog=EXAMPLES_HEADER
    + "  scitex-orochi serve\n"
    + "  SCITEX_OROCHI_ADMIN_TOKEN=secret scitex-orochi serve\n",
)
@click.pass_context
def serve(ctx: click.Context) -> None:
    """Start the Orochi hub server.

    Admin token is read from $SCITEX_OROCHI_ADMIN_TOKEN
    (auto-generated by _main.py if not set).
    """
    from scitex_orochi._server import main as server_main

    server_main()


# ── setup-push ──────────────────────────────────────────────────
@click.command(
    "setup-push",
    epilog=EXAMPLES_HEADER
    + "  scitex-orochi setup-push\n"
    + "  scitex-orochi setup-push --output /etc/orochi/vapid.json\n"
    + "  scitex-orochi setup-push --dry-run --json\n",
)
@click.option(
    "--output", default=None, help="Output path (default: /data/vapid-keys.json)."
)
@click.option("--force", is_flag=True, help="Overwrite existing keys.")
@click.option("--json", "as_json", is_flag=True, help="Output as JSON.")
@click.option("--dry-run", is_flag=True, help="Show what would happen without writing.")
def setup_push(output: str | None, force: bool, as_json: bool, dry_run: bool) -> None:
    """Set up browser push notifications (generates encryption keys)."""
    from scitex_orochi._push import (
        generate_vapid_keys,
        get_vapid_keys_path,
        load_vapid_keys,
        save_vapid_keys,
    )

    path = output or str(get_vapid_keys_path())

    if dry_run:
        existing = load_vapid_keys(path)
        result = {
            "action": "vapid-generate",
            "output": path,
            "exists": existing is not None,
            "force": force,
        }
        if as_json:
            click.echo(json.dumps(result, indent=2))
        else:
            if existing and not force:
                click.echo(
                    f"[dry-run] Keys already exist at {path} (use --force to overwrite)"
                )
            else:
                click.echo(f"[dry-run] Would generate VAPID keys at {path}")
        return

    existing = load_vapid_keys(path)
    if existing and not force:
        if as_json:
            click.echo(
                json.dumps(
                    {
                        "status": "exists",
                        "path": path,
                        "public_key": existing["public_key"],
                    }
                )
            )
        else:
            click.echo(f"VAPID keys already exist at {path}")
            click.echo(f"Public key: {existing['public_key']}")
            click.echo("Use --force to regenerate.")
        return

    keys = generate_vapid_keys()
    save_vapid_keys(keys, path)
    if as_json:
        click.echo(
            json.dumps(
                {
                    "status": "generated",
                    "path": path,
                    "public_key": keys["public_key"],
                }
            )
        )
    else:
        click.echo(f"VAPID keys generated and saved to {path}")
        click.echo(f"Public key: {keys['public_key']}")


# ── Phase 1d Step C: register verbs under the noun group ───────────────
# ``server start`` (was flat ``serve``), ``server status`` (was flat
# ``show-status``), ``server deploy`` (was flat ``deploy`` group with
# stable/dev/status subcommands — the whole group moves under ``server``
# wholesale).
from scitex_orochi._cli.commands.deploy_cmd import deploy as _deploy_group
from scitex_orochi._cli.commands.query_cmd import show_status as _show_status

server.add_command(serve, name="start")
server.add_command(_show_status, name="status")
server.add_command(_deploy_group, name="deploy")

annotate_help_with_availability(server)
