"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package(
        "scitex-orochi",
        skip_rules=(
            # Test-hygiene backlog: the no-mocks (PA-306) and
            # test-quality (PA-307) rules ship at error severity but
            # post-date this suite. orochi's `.scitex/dev/config.yaml`
            # already marks the project `deferred`, which suppresses
            # PA-306/307 locally — but audit-python-apis resolves its
            # config repo-root from the ECOSYSTEM registry's dev-box
            # `local_path` (~/proj/scitex-orochi), which does not exist
            # on CI runners, so the deferral cannot apply there. Masked
            # here (the same way scitex-io / scitex-cloud do) so the
            # gate stays green while the ecosystem TQ-migration
            # (de-mocking + AAA-splitting) lands incrementally. The
            # tests themselves still run and pass.
            "PA-306",
            "PA-307",
        ),
    )
