// Auto-generated ambient declarations for orochi-hub classic-script globals.
// Every top-level `function` / `var` / `let` / `const` across
// hub/static/hub/**/*.js is declared here as `any` so the migrated
// TS files keep compiling without per-site refactors to imports.
// Narrow these to per-module types once the migration settles.

export {};

declare global {
  // Browser APIs — loosen for the big-bang migration.
  interface Window {
    [key: string]: any;
  }

  // Common external libs attached to window in dashboard.html
  const mermaid: any;
  const hljs: any;

  // ---------------- Top-level functions (456) ----------------
  function _activateTab(...args: any[]): any;
  function _activityPaneCloseSsh(...args: any[]): any;
  function _activityPaneOpenSsh(...args: any[]): any;
  function _addAgentContextMenu(...args: any[]): any;
  function _addChannelContextMenu(...args: any[]): any;
  function _addDragAndDrop(...args: any[]): any;
  function _agentCtxKeyHandler(...args: any[]): any;
  function _agentDjangoUsername(...args: any[]): any;
  function _agentDmCreate(...args: any[]): any;
  function _agentHasChannel(...args: any[]): any;
  function _agentSubscribe(...args: any[]): any;
  function _appendReplyToPanel(...args: any[]): any;
  function _applyMachinesViewVisibility(...args: any[]): any;
  function _applyOverviewViewClass(...args: any[]): any;
  function _applyTodoViewMode(...args: any[]): any;
  function _backgroundFillDetails(...args: any[]): any;
  function _bindActivityChannelControls(...args: any[]): any;
  function _bindActivityPaneControls(...args: any[]): any;
  function _bindActivitySendInput(...args: any[]): any;
  function _bindChannelControls(...args: any[]): any;
  function _bindPaneControls(...args: any[]): any;
  function _bindSubTabBar(...args: any[]): any;
  function _buildIndicatorLamps(...args: any[]): any;
  function _buildLineChartSVG(...args: any[]): any;
  function _buildOverviewHtml(...args: any[]): any;
  function _buildParentPreview(...args: any[]): any;
  function _buildPastedTextFile(...args: any[]): any;
  function _buildRenderRows(...args: any[]): any;
  function _buildSidebarMemoryChipsHtml(...args: any[]): any;
  function _buildSidebarMemoryDropdownOptions(...args: any[]): any;
  function _buildVizSkeleton(...args: any[]): any;
  function _buildWebcamUI(...args: any[]): any;
  function _channelMatchesIsFlag(...args: any[]): any;
  function _chatFilterApplyNow(...args: any[]): any;
  function _clearDragIndicators(...args: any[]): any;
  function _closeTopoGroupCompose(...args: any[]): any;
  function _colorKeyFor(...args: any[]): any;
  function _computeAgentState(...args: any[]): any;
  function _csrfTokenForChannels(...args: any[]): any;
  function _currentInputTokens(...args: any[]): any;
  function _dmFriendlyLabel(...args: any[]): any;
  function _draftKey(...args: any[]): any;
  function _edgePath(...args: any[]): any;
  function _ensureAttachmentTray(...args: any[]): any;
  function _ensureAvatarInput(...args: any[]): any;
  function _ensureDetailFilled(...args: any[]): any;
  function _ensureHumanAvatarInput(...args: any[]): any;
  function _fetchCrossRepoTitle(...args: any[]): any;
  function _fmtDuration(...args: any[]): any;
  function _fmtMetricPct(...args: any[]): any;
  function _fmtTs(...args: any[]): any;
  function _formatIdle(...args: any[]): any;
  function _formatUptime(...args: any[]): any;
  function _friendlyMachine(...args: any[]): any;
  function _getCsrf(...args: any[]): any;
  function _hasBlockerLabel(...args: any[]): any;
  function _hideAgentCtxMenu(...args: any[]): any;
  function _hideChannelCtxMenu(...args: any[]): any;
  function _hydrateIssueLink(...args: any[]): any;
  function _identityAgentColorKey(...args: any[]): any;
  function _identityAgentDisplay(...args: any[]): any;
  function _identityColor(...args: any[]): any;
  function _imgViewerKeyHandler(...args: any[]): any;
  function _incrementThreadCountBadge(...args: any[]): any;
  function _initFilterChips(...args: any[]): any;
  function _invalidateAgentDetail(...args: any[]): any;
  function _invalidateTopoPerms(...args: any[]): any;
  function _isDeadAgent(...args: any[]): any;
  function _isTagsFrom(...args: any[]): any;
  function _layoutNodes(...args: any[]): any;
  function _legacyRenderAgentLeds(...args: any[]): any;
  function _linkifyIssues(...args: any[]): any;
  function _linkifyThreadContent(...args: any[]): any;
  function _livenessLabel(...args: any[]): any;
  function _livenessOrder(...args: any[]): any;
  function _machineMetricsHtml(...args: any[]): any;
  function _machineTooltip(...args: any[]): any;
  function _markerAttrsForPerm(...args: any[]): any;
  function _matchAllWords(...args: any[]): any;
  function _mentionRegex(...args: any[]): any;
  function _mermaidSvgToImg(...args: any[]): any;
  function _openAgentDm(...args: any[]): any;
  function _openAgentDmSimple(...args: any[]): any;
  function _openTopoGroupCompose(...args: any[]): any;
  function _ovgWireClick(...args: any[]): any;
  function _ovgWireContextmenu(...args: any[]): any;
  function _ovgWireHover(...args: any[]): any;
  function _ovgWireMouse(...args: any[]): any;
  function _parseCurrentTask(...args: any[]): any;
  function _passesGroupFilter(...args: any[]): any;
  function _pastedTextShouldAttach(...args: any[]): any;
  function _pdfModalEscHandler(...args: any[]): any;
  function _pdfModalPopstateHandler(...args: any[]): any;
  function _permKey(...args: any[]): any;
  function _persistMachineIcons(...args: any[]): any;
  function _populateIssueMap(...args: any[]): any;
  function _positionMachineTooltip(...args: any[]): any;
  function _processMessageMarkdown(...args: any[]): any;
  function _pulseSidebarRow(...args: any[]): any;
  function _pushThreadUrlState(...args: any[]): any;
  function _readThreadIdFromUrl(...args: any[]): any;
  function _rebuildAgentChannelMap(...args: any[]): any;
  function _refreshTopoPerms(...args: any[]): any;
  function _renderActivityAgentDetail(...args: any[]): any;
  function _renderActivityCards(...args: any[]): any;
  function _renderActivityTopology(...args: any[]): any;
  function _renderAgentContent(...args: any[]): any;
  function _renderAgentDetail(...args: any[]): any;
  function _renderAttachmentTray(...args: any[]): any;
  function _renderBlockersSidebar(...args: any[]): any;
  function _renderChannelRowHtml(...args: any[]): any;
  function _renderFolderRowHtml(...args: any[]): any;
  function _renderHealthField(...args: any[]): any;
  function _renderHookPanels(...args: any[]): any;
  function _renderIndicatorLamps(...args: any[]): any;
  function _renderMembersPanel(...args: any[]): any;
  function _renderMermaidIn(...args: any[]): any;
  function _renderStarredSection(...args: any[]): any;
  function _renderSubTabBar(...args: any[]): any;
  function _renderTaskField(...args: any[]): any;
  function _renderThreadAttachmentTray(...args: any[]): any;
  function _renderTodoFromCache(...args: any[]): any;
  function _renderTodoStats(...args: any[]): any;
  function _renderTodoStatsBurndown(...args: any[]): any;
  function _renderTodoStatsByRepo(...args: any[]): any;
  function _renderTodoStatsLabels(...args: any[]): any;
  function _renderTodoStatsStarvation(...args: any[]): any;
  function _renderTodoStatsTotals(...args: any[]): any;
  function _renderVizPayload(...args: any[]): any;
  function _repaintTopoArrows(...args: any[]): any;
  function _repositionMenuInViewport(...args: any[]): any;
  function _saveDraft(...args: any[]): any;
  function _secondsSinceIso(...args: any[]): any;
  function _setAgentIcon(...args: any[]): any;
  function _setChannelDropHint(...args: any[]): any;
  function _setChannelIcon(...args: any[]): any;
  function _setChannelPref(...args: any[]): any;
  function _shortRepo(...args: any[]): any;
  function _showAgentContextMenu(...args: any[]): any;
  function _showChannelCtxMenu(...args: any[]): any;
  function _showMiniToast(...args: any[]): any;
  function _sidebarMemoryRefreshBothSurfaces(...args: any[]): any;
  function _sidebarMemoryShowHint(...args: any[]): any;
  function _sortedStarred(...args: any[]): any;
  function _splitChannelPath(...args: any[]): any;
  function _startActivityFollow(...args: any[]): any;
  function _startFollow(...args: any[]): any;
  function _stopActivityFollow(...args: any[]): any;
  function _stopFollow(...args: any[]): any;
  function _stripAnsi(...args: any[]): any;
  function _submitTopoMentionPost(...args: any[]): any;
  function _syncFilterChips(...args: any[]): any;
  function _syncMemoryDirtyIndicators(...args: any[]): any;
  function _syncTodoBtnState(...args: any[]): any;
  function _termCloseExisting(...args: any[]): any;
  function _termHandleWindowResize(...args: any[]): any;
  function _termLoadAssets(...args: any[]): any;
  function _termRenderPicker(...args: any[]): any;
  function _termStatus(...args: any[]): any;
  function _todoBackendState(...args: any[]): any;
  function _todoViewMode(...args: any[]): any;
  function _toggleAgentChannelSubscription(...args: any[]): any;
  function _toggleIsToken(...args: any[]): any;
  function _topoApplyStickyEdges(...args: any[]): any;
  function _topoAutoSaveActiveSlot(...args: any[]): any;
  function _topoBuildAgentsSvg(...args: any[]): any;
  function _topoBuildChannelsSvg(...args: any[]): any;
  function _topoBuildEdgesHtml(...args: any[]): any;
  function _topoBuildHumanSvg(...args: any[]): any;
  function _topoBuildPoolHtml(...args: any[]): any;
  function _topoBumpClick(...args: any[]): any;
  function _topoClampMenuInViewport(...args: any[]): any;
  function _topoCleanupDrag(...args: any[]): any;
  function _topoClearDrop(...args: any[]): any;
  function _topoClearManualPosition(...args: any[]): any;
  function _topoCloseEdgeMenu(...args: any[]): any;
  function _topoDoEdgeUnsubscribe(...args: any[]): any;
  function _topoEdgeMenuKeyHandler(...args: any[]): any;
  function _topoEdgeMenuOutsideClick(...args: any[]): any;
  function _topoFlashEdge(...args: any[]): any;
  function _topoFlushClick(...args: any[]): any;
  function _topoHiddenSignature(...args: any[]): any;
  function _topoHide(...args: any[]): any;
  function _topoLandingBubble(...args: any[]): any;
  function _topoManualKey(...args: any[]): any;
  function _topoManualPositionsSignature(...args: any[]): any;
  function _topoMemWorkspaceKey(...args: any[]): any;
  function _topoOpenChannelCompose(...args: any[]): any;
  function _topoPersistActiveMemSlot(...args: any[]): any;
  function _topoPoolApplyCanvasFilter(...args: any[]): any;
  function _topoPoolMemoryDelete(...args: any[]): any;
  function _topoPoolMemoryIsDirty(...args: any[]): any;
  function _topoPoolMemoryNextFreeSlot(...args: any[]): any;
  function _topoPoolMemoryRecall(...args: any[]): any;
  function _topoPoolMemoryRename(...args: any[]): any;
  function _topoPoolMemorySave(...args: any[]): any;
  function _topoPoolMemorySnapshot(...args: any[]): any;
  function _topoPoolPersistMemories(...args: any[]): any;
  function _topoPoolPersistSelection(...args: any[]): any;
  function _topoPoolSelectAll(...args: any[]): any;
  function _topoPoolSelectClear(...args: any[]): any;
  function _topoPoolSelectOnly(...args: any[]): any;
  function _topoPoolSelectRange(...args: any[]): any;
  function _topoPoolSelectToggle(...args: any[]): any;
  function _topoPoolSelectionHas(...args: any[]): any;
  function _topoPoolSelectionPaint(...args: any[]): any;
  function _topoPoolSelectionSize(...args: any[]): any;
  function _topoPulseEdge(...args: any[]): any;
  function _topoSaveHidden(...args: any[]): any;
  function _topoSaveManualPositions(...args: any[]): any;
  function _topoSeekBuffer(...args: any[]): any;
  function _topoSeekEnterLive(...args: any[]): any;
  function _topoSeekEnterPlayback(...args: any[]): any;
  function _topoSeekFormatLabel(...args: any[]): any;
  function _topoSeekHeatColor(...args: any[]): any;
  function _topoSeekHeatCompute(...args: any[]): any;
  function _topoSeekHeatPaint(...args: any[]): any;
  function _topoSeekHeatRefresh(...args: any[]): any;
  function _topoSeekReplayOne(...args: any[]): any;
  function _topoSeekStartPlay(...args: any[]): any;
  function _topoSeekStopPlay(...args: any[]): any;
  function _topoSeekTogglePlay(...args: any[]): any;
  function _topoSeekUpdateUI(...args: any[]): any;
  function _topoSeekbarHtml(...args: any[]): any;
  function _topoSelectAdd(...args: any[]): any;
  function _topoSelectClear(...args: any[]): any;
  function _topoSelectToggle(...args: any[]): any;
  function _topoSelectedNames(...args: any[]): any;
  function _topoSetManualPosition(...args: any[]): any;
  function _topoShowEdgeMenu(...args: any[]): any;
  function _topoShowSubscribeToast(...args: any[]): any;
  function _topoSignature(...args: any[]): any;
  function _topoSpawnGhost(...args: any[]): any;
  function _topoSpawnPacket(...args: any[]): any;
  function _topoStickyKey(...args: any[]): any;
  function _topoSvgPoint(...args: any[]): any;
  function _topoUnhide(...args: any[]): any;
  function _topoUnhideAll(...args: any[]): any;
  function _updateChannelTopicBanner(...args: any[]): any;
  function _updateComposerTarget(...args: any[]): any;
  function _updateImgViewer(...args: any[]): any;
  function _updateLastFetchedLabel(...args: any[]): any;
  function _updateTodoBtnCounts(...args: any[]): any;
  function _vizSig(...args: any[]): any;
  function _webcamEnsureFallbackInput(...args: any[]): any;
  function _webcamOpenFallback(...args: any[]): any;
  function _webcamStopStream(...args: any[]): any;
  function _webcamWireFallbackInput(...args: any[]): any;
  function _wireChannelItemHandlers(...args: any[]): any;
  function _wireMachinesControls(...args: any[]): any;
  function _wireOverviewControls(...args: any[]): any;
  function _wireOverviewGridDelegation(...args: any[]): any;
  function _wireSettingsIconPicker(...args: any[]): any;
  function _wireSidebarMemory(...args: any[]): any;
  function _wireTodoViewSwitch(...args: any[]): any;
  function _wireTopoEscCancel(...args: any[]): any;
  function _wireTopoSeekbar(...args: any[]): any;
  function _wireTopoZoomPan(...args: any[]): any;
  function addTag(...args: any[]): any;
  function agentIdentity(...args: any[]): any;
  function apiUrl(...args: any[]): any;
  function appendMessage(...args: any[]): any;
  function appendSystemMessage(...args: any[]): any;
  function appendToThreadPanelIfOpen(...args: any[]): any;
  function applyFeedFilter(...args: any[]): any;
  function applyIssueTitleHints(...args: any[]): any;
  function applyThreadUrlOnLoad(...args: any[]): any;
  function attachDragHandlers(...args: any[]): any;
  function attachTodoEvents(...args: any[]): any;
  function barHtml(...args: any[]): any;
  function buildAgentRow(...args: any[]): any;
  function buildAttachmentsHtml(...args: any[]): any;
  function buildDetailInnerHtml(...args: any[]): any;
  function buildGroupHtml(...args: any[]): any;
  function buildIssueCard(...args: any[]): any;
  function buildLabelsHtml(...args: any[]): any;
  function buildResourceCard(...args: any[]): any;
  function buildWorkspaceCard(...args: any[]): any;
  function cacheAgentIcons(...args: any[]): any;
  function cacheChannelIdentity(...args: any[]): any;
  function cancelEditMessage(...args: any[]): any;
  function captureWebcamFrame(...args: any[]): any;
  function channelIdentity(...args: any[]): any;
  function chatFilterApply(...args: any[]): any;
  function chatFilterReset(...args: any[]): any;
  function classifyIssue(...args: any[]): any;
  function cleanAgentName(...args: any[]): any;
  function cleanDisplayName(...args: any[]): any;
  function clearPendingAttachments(...args: any[]): any;
  function closeChannelExport(...args: any[]): any;
  function closeChannelTopicEdit(...args: any[]): any;
  function closeImgViewer(...args: any[]): any;
  function closeMembersPanel(...args: any[]): any;
  function closePdfViewer(...args: any[]): any;
  function closeReactionPicker(...args: any[]): any;
  function closeSketch(...args: any[]): any;
  function closeThreadPanel(...args: any[]): any;
  function closeWebcam(...args: any[]): any;
  function connect(...args: any[]): any;
  function copyThreadPermalink(...args: any[]): any;
  function copyToken(...args: any[]): any;
  function deleteMessage(...args: any[]): any;
  function deleteRepo(...args: any[]): any;
  function doChannelExport(...args: any[]): any;
  function donutHtml(...args: any[]): any;
  function escapeHtml(...args: any[]): any;
  function fetchAgentsThrottled(...args: any[]): any;
  function fetchHumanProfiles(...args: any[]): any;
  function fetchSettings(...args: any[]): any;
  function fetchStatsThrottled(...args: any[]): any;
  function fetchTrackedRepos(...args: any[]): any;
  function fetchWorkspaceInvites(...args: any[]): any;
  function filesClearSelection(...args: any[]): any;
  function filesDownloadSelected(...args: any[]): any;
  function filesHandleClick(...args: any[]): any;
  function filesMatchQuery(...args: any[]): any;
  function filesSetPreviewIdx(...args: any[]): any;
  function filesSetQuery(...args: any[]): any;
  function filesSetView(...args: any[]): any;
  function filesTogglePreview(...args: any[]): any;
  function filterMessages(...args: any[]): any;
  function filterSidebarElements(...args: any[]): any;
  function formatDate(...args: any[]): any;
  function formatFileSize(...args: any[]): any;
  function formatUptime(...args: any[]): any;
  function fuzzyMatch(...args: any[]): any;
  function getAgentColor(...args: any[]): any;
  function getCsrfToken(...args: any[]): any;
  function getLetterIcon(...args: any[]): any;
  function getMentionQuery(...args: any[]): any;
  function getPendingAttachments(...args: any[]): any;
  function getPersonIcon(...args: any[]): any;
  function getResolvedAgentColor(...args: any[]): any;
  function getSenderIcon(...args: any[]): any;
  function getSnakeIcon(...args: any[]): any;
  function getSnakeLogo(...args: any[]): any;
  function getTagSuggestions(...args: any[]): any;
  function getWorkspaceColor(...args: any[]): any;
  function getWorkspaceIcon(...args: any[]): any;
  function handleClipboardPaste(...args: any[]): any;
  function handleMentionBlur(...args: any[]): any;
  function handleMentionInput(...args: any[]): any;
  function handleMentionKeydown(...args: any[]): any;
  function handleMessage(...args: any[]): any;
  function handleMessageDelete(...args: any[]): any;
  function handleMessageEdit(...args: any[]): any;
  function handleReactionUpdate(...args: any[]): any;
  function handleThreadReply(...args: any[]): any;
  function healthColor(...args: any[]): any;
  function hideMachineTooltip(...args: any[]): any;
  function hideMentionDropdown(...args: any[]): any;
  function hideSuggestions(...args: any[]): any;
  function hostedAgentName(...args: any[]): any;
  function imgViewerNav(...args: any[]): any;
  function initMentionAutocomplete(...args: any[]): any;
  function initPushUI(...args: any[]): any;
  function initReleasesTab(...args: any[]): any;
  function insertMention(...args: any[]): any;
  function isAgentInactive(...args: any[]): any;
  function isAgentOnline(...args: any[]): any;
  function isKnownAgent(...args: any[]): any;
  function isLightColor(...args: any[]): any;
  function jumpToMsg(...args: any[]): any;
  function livenessColor(...args: any[]): any;
  function loadChangelog(...args: any[]): any;
  function matchesAllTags(...args: any[]): any;
  function matchesFilter(...args: any[]): any;
  function messageKey(...args: any[]): any;
  function mimeCategory(...args: any[]): any;
  function moveMachineTooltip(...args: any[]): any;
  function normalizeBody(...args: any[]): any;
  function onAgentInfoEvent(...args: any[]): any;
  function openAddRepoDialog(...args: any[]): any;
  function openAvatarPicker(...args: any[]): any;
  function openChannelExport(...args: any[]): any;
  function openChannelTopicEdit(...args: any[]): any;
  function openHumanAvatarPicker(...args: any[]): any;
  function openHumanAvatarTextEditor(...args: any[]): any;
  function openImgViewer(...args: any[]): any;
  function openMembersPanel(...args: any[]): any;
  function openPdfViewer(...args: any[]): any;
  function openReactionPicker(...args: any[]): any;
  function openSketch(...args: any[]): any;
  function openTerminalForHost(...args: any[]): any;
  function openThreadForMessage(...args: any[]): any;
  function orochiHeaders(...args: any[]): any;
  function paneStateColor(...args: any[]): any;
  function parseFilterInput(...args: any[]): any;
  function persistOrder(...args: any[]): any;
  function positionMentionDropdown(...args: any[]): any;
  function relativeAge(...args: any[]): any;
  function removeTag(...args: any[]): any;
  function renderActivityTab(...args: any[]): any;
  function renderCompactPolicySuffix(...args: any[]): any;
  function renderConnectivityMap(...args: any[]): any;
  function renderContextBadge(...args: any[]): any;
  function renderFilePreview(...args: any[]): any;
  function renderFilesGrid(...args: any[]): any;
  function renderFilesPreview(...args: any[]): any;
  function renderMarkdown(...args: any[]): any;
  function renderMyAvatarButton(...args: any[]): any;
  function renderPaneStateBadge(...args: any[]): any;
  function renderReactionsForMessage(...args: any[]): any;
  function renderResources(...args: any[]): any;
  function renderResourcesTab(...args: any[]): any;
  function renderSidebarMemory(...args: any[]): any;
  function renderSkillsBadge(...args: any[]): any;
  function renderSubtabs(...args: any[]): any;
  function renderTags(...args: any[]): any;
  function renderTerminalTab(...args: any[]): any;
  function renderVizTab(...args: any[]): any;
  function renderWorkspacesTab(...args: any[]): any;
  function restoreDraftForCurrentChannel(...args: any[]): any;
  function runFilter(...args: any[]): any;
  function saveChannelTopic(...args: any[]): any;
  function saveEditMessage(...args: any[]): any;
  function selectRepo(...args: any[]): any;
  function sendMessage(...args: any[]): any;
  function sendOrochiMessage(...args: any[]): any;
  function setCurrentChannel(...args: any[]): any;
  function setMachineIcon(...args: any[]): any;
  function setupSketchEvents(...args: any[]): any;
  function showMachineTooltip(...args: any[]): any;
  function showMentionDropdown(...args: any[]): any;
  function showSuggestions(...args: any[]): any;
  function showSystemBanner(...args: any[]): any;
  function sortByUpdated(...args: any[]): any;
  function startActivityAutoRefresh(...args: any[]): any;
  function startAgentsTabRefresh(...args: any[]): any;
  function startBlockersPoll(...args: any[]): any;
  function startEditMessage(...args: any[]): any;
  function startRestPolling(...args: any[]): any;
  function startTodoStatsAutoRefresh(...args: any[]): any;
  function stopActivityAutoRefresh(...args: any[]): any;
  function stopAgentsTabRefresh(...args: any[]): any;
  function stopRestPolling(...args: any[]): any;
  function stopTerminalTab(...args: any[]): any;
  function stopTodoStatsAutoRefresh(...args: any[]): any;
  function stopVizTab(...args: any[]): any;
  function syncFilterVisuals(...args: any[]): any;
  function syncHostHover(...args: any[]): any;
  function threadPermalinkUrl(...args: any[]): any;
  function timeAgo(...args: any[]): any;
  function toggleClaudeMd(...args: any[]): any;
  function toggleMembersPanel(...args: any[]): any;
  function toggleToken(...args: any[]): any;
  function updateChannelSelect(...args: any[]): any;
  function updateChannelUnreadBadges(...args: any[]): any;
  function updatePushToggleUI(...args: any[]): any;
  function updateResourcePanel(...args: any[]): any;
  function uploadAgentAvatar(...args: any[]): any;
  function uploadHumanAvatar(...args: any[]): any;
  function uptime(...args: any[]): any;
  function urlBase64ToUint8Array(...args: any[]): any;
  function wireSettingsForms(...args: any[]): any;
  function wireSettingsModeTabs(...args: any[]): any;

  // ---------------- Top-level var/let/const (211) ----------------
  var ACTIVITY_FOLLOW_INTERVAL_MS: any;
  var CACHE_NAME: any;
  var COMMON_EMOJI: any;
  var FETCH_AGENTS_THROTTLE_MS: any;
  var FOLLOW_INTERVAL_MS: any;
  var IS_FLAGS: any;
  var MACHINE_ALIASES: any;
  var OROCHI_COLORS: any;
  var PASTE_TEXT_ATTACH_MIN_CHARS: any;
  var PASTE_TEXT_ATTACH_MIN_LINES: any;
  var PRIORITY_GROUPS: any;
  var REPOS: any;
  var SHELL_ASSETS: any;
  var SKETCH_COLORS: any;
  var SKETCH_WIDTHS: any;
  var SKETCH_WIDTH_LABELS: any;
  var SPECIAL_MENTIONS: any;
  var TERMINAL_HOSTS: any;
  var TOPO_CLICK_WINDOW_MS: any;
  var TOPO_PERMS_TTL_MS: any;
  var TOPO_SEEK_HEAT_BINS: any;
  var TOPO_SEEK_HEAT_THROTTLE_MS: any;
  var TOPO_SEEK_WINDOW_MS: any;
  var WORKSPACE_ICON_COLORS: any;
  var _BLOCKERS_POLL_MS: any;
  var _MACHINE_ICON_KEY: any;
  var _TODO_CACHE_TTL_MS: any;
  var _TODO_STATS_REFRESH_MS: any;
  var _TODO_VIEW_KEY: any;
  var _TOPO_ACTIVE_MEM_KEY: any;
  var _TOPO_LANDING_DUR_MS: any;
  var _TOPO_LANDING_STACK_MAX: any;
  var _TOPO_LANDING_STEP_PX: any;
  var _TOPO_POOL_MEM_KEY_LEGACY: any;
  var _TOPO_POOL_MEM_MAX: any;
  var _TOPO_POOL_SEL_KEY: any;
  var _VIZ_FRESH_MS: any;
  var _activityDetailCache: any;
  var _activityDetailInflight: any;
  var _activityFollowAgent: any;
  var _activityFollowTimer: any;
  var _activityPaneExpanded: any;
  var _activityPaneSshState: any;
  var _agentChannelMap: any;
  var _agentCtxMenu: any;
  var _agentDetailCache: any;
  var _agentDetailInflight: any;
  var _agentsTabInterval: any;
  var _attachmentTray: any;
  var _avatarFileInput: any;
  var _avatarTargetAgent: any;
  var _blockersRefreshTimer: any;
  var _channelDescriptions: any;
  var _channelPrefs: any;
  var _chatFilterDebounce: any;
  var _chatFilterQuery: any;
  var _ctxMenu: any;
  var _dndState: any;
  var _dragSrcId: any;
  var _fetchAgentsPending: any;
  var _fetchAgentsTimer: any;
  var _fetchStatsPending: any;
  var _fetchStatsTimer: any;
  var _fm: any;
  var _followAgent: any;
  var _followTimer: any;
  var _humanAvatarFileInput: any;
  var _initialLoadComplete: any;
  var _isLoadingHistory: any;
  var _lastAgentsData: any;
  var _machineIcons: any;
  var _machineTooltipEl: any;
  var _machinesControlsWired: any;
  var _machinesView: any;
  var _membersCache: any;
  var _mentionRegexCache: any;
  var _overviewColor: any;
  var _overviewControlsWired: any;
  var _overviewExpanded: any;
  var _overviewFilter: any;
  var _overviewGridWired: any;
  var _overviewSort: any;
  var _overviewView: any;
  var _paneExpanded: any;
  var _paneShowRaw: any;
  var _selectedAgentTab: any;
  var _termState: any;
  var _threadSketchActive: any;
  var _todoCache: any;
  var _todoCacheTs: any;
  var _todoIssuesByNumber: any;
  var _todoStatsRefreshTimer: any;
  var _topoActiveMemSlot: any;
  var _topoChannelPerms: any;
  var _topoChannelPermsFetchedAt: any;
  var _topoChannelPermsInflight: any;
  var _topoClickState: any;
  var _topoComposeEl: any;
  var _topoComposeEscapeHandler: any;
  var _topoDragState: any;
  var _topoEdgeMenuEl: any;
  var _topoEscWired: any;
  var _topoHidden: any;
  var _topoLandingStacks: any;
  var _topoLastExpanded: any;
  var _topoLastPositions: any;
  var _topoLastSig: any;
  var _topoManualPositions: any;
  var _topoPoolMemories: any;
  var _topoPoolSelAnchor: any;
  var _topoPoolSelection: any;
  var _topoSeekEvents: any;
  var _topoSeekHeatLastPaint: any;
  var _topoSeekHeatLastSig: any;
  var _topoSeekInteracting: any;
  var _topoSeekLastFrameTs: any;
  var _topoSeekMode: any;
  var _topoSeekPlaying: any;
  var _topoSeekRafId: any;
  var _topoSeekReplayInProgress: any;
  var _topoSeekSpeed: any;
  var _topoSeekTime: any;
  var _topoSeekWired: any;
  var _topoSelected: any;
  var _topoSizeBy: any;
  var _topoStickyEdges: any;
  var _topoViewBox: any;
  var _topoViewBoxFuture: any;
  var _topoViewBoxHistory: any;
  var _topoZoomWired: any;
  var _vizCachedAt: any;
  var _vizCachedData: any;
  var _vizPollTimer: any;
  var _vizRenderedSig: any;
  var _voiceDeferQueue: any;
  var _webcamBtn: any;
  var activeRepoKey: any;
  var activeTab: any;
  var activeTags: any;
  var activityRefreshTimer: any;
  var baseTitle: any;
  var cachedAgentColors: any;
  var cachedAgentIcons: any;
  var cachedAgentNames: any;
  var cachedAgentObjects: any;
  var cachedChannelColors: any;
  var cachedChannelIcons: any;
  var cachedHumanColors: any;
  var cachedHumanIcons: any;
  var cachedMemberNames: any;
  var changelogCache: any;
  var channelUnread: any;
  var connectivityCache: any;
  var csrfToken: any;
  var currentChannel: any;
  var filesCache: any;
  var filesFilterMime: any;
  var filesPreviewIdx: any;
  var filesPreviewVisible: any;
  var filesQuery: any;
  var filesSelected: any;
  var filesViewMode: any;
  var filterInput: any;
  var filterSuggestEl: any;
  var filterTagsEl: any;
  var historyLoaded: any;
  var imgViewerIdx: any;
  var imgViewerImages: any;
  var issueTitleCache: any;
  var issueTitleInflight: any;
  var knownMessageKeys: any;
  var lastActiveChannel: any;
  var mentionActiveInput: any;
  var mentionDropdown: any;
  var mentionSelectedIndex: any;
  var msgInput: any;
  var origTabClick: any;
  var pendingAttachments: any;
  var pushEnabled: any;
  var pushSubscription: any;
  var pushSupported: any;
  var reactionPicker: any;
  var releasesInitialized: any;
  var resourceData: any;
  var restPollInterval: any;
  var restPollTimer: any;
  var settingsLoaded: any;
  var sketchCanvas: any;
  var sketchColor: any;
  var sketchCtx: any;
  var sketchDrawing: any;
  var sketchLineWidth: any;
  var sketchOverlay: any;
  var sketchTool: any;
  var suggestIndex: any;
  var threadPanel: any;
  var threadPanelParentId: any;
  var threadPendingAttachments: any;
  var todoActiveGroups: any;
  var token: any;
  var unreadCount: any;
  var userName: any;
  var webcamCaptureInput: any;
  var webcamFacing: any;
  var webcamOnKey: any;
  var webcamOverlay: any;
  var webcamStream: any;
  var webcamVideo: any;
  var workspacesData: any;
  var ws: any;
  var wsConnected: any;
}
