/* Minimal flat ESLint config for the hub TS bundle.
 * Most files start with `// @ts-nocheck` because the migration prioritised
 * runtime correctness over type purity. This config is intentionally
 * permissive — it only catches outright bugs, not style/types.
 *
 * Strict typing is a follow-up task; do not tighten this until every
 * file's @ts-nocheck is removed (see GITIGNORED/migration/collisions.md
 * for context). */
export default [
  {
    files: ["src/**/*.{ts,js}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        WebSocket: "readonly",
        XMLHttpRequest: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        EventSource: "readonly",
        Notification: "readonly",
        crypto: "readonly",
        atob: "readonly",
        btoa: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        Symbol: "readonly",
        globalThis: "readonly",
        performance: "readonly",
        confirm: "readonly",
        alert: "readonly",
        prompt: "readonly",
        Audio: "readonly",
        AudioContext: "readonly",
        webkitAudioContext: "readonly",
        SpeechRecognition: "readonly",
        webkitSpeechRecognition: "readonly",
        DOMParser: "readonly",
        Range: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLAudioElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        DragEvent: "readonly",
        ClipboardEvent: "readonly",
        SVGElement: "readonly",
      },
    },
    rules: {
      // Permissive baseline; tighten later.
      "no-unused-vars": "off",
      "no-undef": "off",
      "no-empty": "off",
      "no-prototype-builtins": "off",
      "no-cond-assign": "off",
      "no-self-assign": "off",
      "no-control-regex": "off",
      "no-useless-escape": "off",
      "no-misleading-character-class": "off",
      "no-irregular-whitespace": "off",
      "no-redeclare": "off",
      "no-async-promise-executor": "off",
      // Real bugs — keep as errors:
      "no-debugger": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-unreachable": "error",
    },
  },
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "../static/hub/dist/**",
      "src/globals.d.ts",
    ],
  },
];
