# Generated by Django 5.2.13 on 2026-04-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_reactions_and_threads'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='hub_message_message_5ea540_idx',
            old_name='hub_msgreac_message_idx',
        ),
    ]
