# Generated by Django 5.2.13 on 2026-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_agentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='health_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='health_source',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='health_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='health_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
