# Generated by Django 5.2.7 on 2026-04-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_agentprofile_health_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(blank=True, default="", max_length=100)),
                ("machine", models.CharField(blank=True, default="", max_length=200)),
                ("icon_emoji", models.CharField(blank=True, default="", max_length=16)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_agents",
                        to="hub.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("workspace", "name")},
            },
        ),
    ]
