# Generated by Django 5.2.7 on 2026-04-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0009_add_pinned_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="color",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
