# Generated by Django 5.2.13 on 2026-04-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_containeragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('public', 'Public'), ('dm', 'Direct Message')], db_index=True, default='public', max_length=16),
        ),
    ]
