# Generated by Django 5.2.13 on 2026-04-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_dedupe_unhashed_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('machine', 'Machine'), ('agent', 'Agent'), ('server', 'Orochi Server'), ('session', 'Claude Session')], max_length=20)),
                ('entity_id', models.CharField(max_length=128)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('source', models.CharField(max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-ts'], name='hub_fleetre_entity__3b6eec_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(help_text='Target agent name', max_length=128)),
                ('task', models.TextField(help_text='Task description to deliver to the agent')),
                ('channel', models.CharField(default='#general', help_text='Channel to deliver the task in', max_length=128)),
                ('run_at', models.DateTimeField(help_text='UTC datetime when the action should fire')),
                ('cron', models.CharField(blank=True, default='', help_text='Optional cron expression for recurring actions (blank = one-shot)', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('created_by', models.CharField(default='', help_text='Creator name', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='hub.workspace')),
            ],
            options={
                'ordering': ['run_at'],
            },
        ),
    ]
