# Generated by Django 5.2.7 on 2026-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0025_inviterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="icon_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
