# Generated by Django 5.2.13 on 2026-04-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0030_agentprofile_last_auto_dispatch_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(db_index=True, max_length=200)),
                (
                    "instance_uuid",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("hostname", models.CharField(blank=True, default="", max_length=200)),
                ("pid", models.IntegerField(blank=True, null=True)),
                (
                    "ws_session_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("cardinality_enforced", models.BooleanField(default=False)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_heartbeat", models.DateTimeField(auto_now=True)),
                ("disconnected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_sessions",
                        to="hub.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["agent_name", "-connected_at"],
                "indexes": [
                    models.Index(
                        fields=["agent_name", "disconnected_at"],
                        name="hub_agentse_agent_n_69e0df_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(db_index=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                (
                    "owner_host",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_snapshots",
                        to="hub.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["agent_name"],
                "unique_together": {("workspace", "agent_name")},
            },
        ),
    ]
