# Generated by Django 5.2.13 on 2026-04-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0030_agentprofile_last_auto_dispatch_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
