# Generated by Django 5.2.10 on 2026-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0033_agent_snapshot_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacetoken",
            name="agent_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
