# Generated by Django 5.2.13 on 2026-04-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0034_alter_workspacetoken_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmembership',
            name='mention_only',
            field=models.BooleanField(default=False, help_text='When True the member receives fan-out only for messages that contain @<member-name>. Silent for all other channel traffic. Used by mamba agents that want low-noise channel presence (todo#406 Phase 2).'),
        ),
    ]
