# Generated by Django 5.2.13 on 2026-04-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0035_channelmembership_mention_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='trust_level',
            field=models.CharField(choices=[('owner', 'Owner'), ('supervisor', 'Supervisor'), ('collaborator', 'Collaborator'), ('guest', 'Guest'), ('unknown', 'Unknown')], default='collaborator', help_text='Controls which agent operations this human may invoke. Independent of workspace role (admin/member).', max_length=12),
        ),
    ]
