# Generated by Django 5.2.13 on 2026-04-29 19:28
# Modified: use SeparateDatabaseAndState so this migration is idempotent on
# instances where the AgentGroup table already exists (created by the original
# 0035_add_agentgroup_model before it was renumbered to 0037).

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models


def _create_agentgroup_if_not_exists(apps, schema_editor):
    if "hub_agentgroup" not in connection.introspection.table_names():
        schema_editor.create_model(apps.get_model("hub", "AgentGroup"))


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0036_workspacemember_trust_level'),
        ('hub', '0035_add_agentgroup_model'),  # stub for deployed instances that already applied the old 0035
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _create_agentgroup_if_not_exists,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='AgentGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Mention key used in @<name> tokens.', max_length=64)),
                        ('display_name', models.CharField(blank=True, default='', max_length=128)),
                        ('description', models.TextField(blank=True, default='')),
                        ('is_builtin', models.BooleanField(default=False, help_text='True for system-seeded groups (heads, mambas, …). Builtin groups cannot be deleted via the API.')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('members', models.ManyToManyField(blank=True, related_name='agent_groups', to=settings.AUTH_USER_MODEL)),
                        ('owner', models.ForeignKey(blank=True, help_text='Creator; null for system-seeded groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agent_groups', to=settings.AUTH_USER_MODEL)),
                        ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_groups', to='hub.workspace')),
                    ],
                    options={
                        'ordering': ['name'],
                        'unique_together': {('workspace', 'name')},
                    },
                ),
            ],
        ),
    ]
