# Generated by Django 5.2.13 on 2026-04-29 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0036_workspacemember_trust_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mention key used in @<name> tokens.', max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_builtin', models.BooleanField(default=False, help_text='True for system-seeded groups (heads, mambas, …). Builtin groups cannot be deleted via the API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='agent_groups', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Creator; null for system-seeded groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agent_groups', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_groups', to='hub.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
