// @ts-nocheck
/* URL hash routing for deep-linkable dashboard views (msg#17039).
 *
 * Scheme: `#<tab>?<filter-params>`
 *   #chat?thread=17004       -> chat view, open thread panel for 17004, scroll+highlight
 *   #chat?channel=heads      -> chat view, select #heads
 *   #overview?thread=17004   -> overview view, highlight that thread
 *   #activity                -> bare tab, legacy form still supported
 *
 * Design notes:
 * - `parseHash()` is the one place to decode the URL. Returns
 *   {tab, params} or null when the hash is empty / malformed.
 *   Unknown params are preserved under `params` but the caller is
 *   responsible for honouring only the keys it cares about.
 * - `writeHash()` uses `history.replaceState` (not pushState) so the
 *   browser's Back button doesn't become a per-tab-switch minefield.
 *   Callers that want a real navigation entry can still call
 *   `history.pushState` themselves.
 * - `onHashChange()` wires a listener for external URL edits (user
 *   pasting a link into the address bar on an already-open tab,
 *   popstate, etc.) and ignores synthetic events generated by our own
 *   `writeHash` calls via the `_suppressNext` gate.
 * - Boot-path: `tabs.ts` calls `parseHash()` BEFORE `readLastOpened()`.
 *   If parseHash returns a concrete state, that wins; else localStorage
 *   restore takes over (PR #358 — last-opened persistence). The two
 *   compose cleanly.
 *
 * Robustness contract (ywatanabe msg#17035):
 *   - Unknown params ignored, not rejected.
 *   - Malformed hash -> returns null, default fallback applies.
 *   - No throws escape this module. */

export type HashState = {
  tab: string;
  params: Record<string, string>;
};

/* Tabs the router is willing to land on. Anything else -> null and
 * the caller falls back to localStorage / default. Keep in sync with
 * the .tab-btn[data-tab=...] set in dashboard.html. Legacy callers
 * (middle-click spawns `#activity` with no params) still parse here. */
const KNOWN_TABS = new Set([
  "activity",
  "chat",
  "todo",
  "agents-tab",
  "resources",
  "workspaces",
  "files",
  "releases",
  "terminal",
  "settings",
]);

/* Module-private flag: when we call writeHash() ourselves, the
 * resulting hashchange is suppressed so we don't re-route off our own
 * update. Flipped true before the assignment, cleared in the listener. */
let _suppressNext = false;

export function parseHash(raw?: string | null): HashState | null {
  try {
    let h = raw != null ? raw : (window.location.hash || "");
    h = String(h).replace(/^#/, "");
    if (!h) return null;
    const qIdx = h.indexOf("?");
    const tabPart = qIdx === -1 ? h : h.slice(0, qIdx);
    const queryPart = qIdx === -1 ? "" : h.slice(qIdx + 1);
    const tab = decodeURIComponent(tabPart || "").trim();
    if (!tab || !KNOWN_TABS.has(tab)) return null;
    const params: Record<string, string> = {};
    if (queryPart) {
      try {
        const sp = new URLSearchParams(queryPart);
        sp.forEach((v, k) => {
          if (k) params[k] = v;
        });
      } catch (_) {
        /* Malformed query string — ignore params, keep tab. */
      }
    }
    return { tab, params };
  } catch (_) {
    return null;
  }
}

/* Serialize state into a hash (without the leading "#"). Empty /
 * undefined params are dropped so `#chat` stays bare rather than
 * becoming `#chat?`. */
export function formatHash(tab: string, params?: Record<string, string | null | undefined>): string {
  const cleanParams: [string, string][] = [];
  if (params) {
    Object.keys(params).forEach((k) => {
      const v = params[k];
      if (v == null || v === "") return;
      cleanParams.push([k, String(v)]);
    });
  }
  if (!cleanParams.length) return tab;
  const sp = new URLSearchParams();
  cleanParams.forEach(([k, v]) => sp.set(k, v));
  return tab + "?" + sp.toString();
}

/* Update window.location.hash via history.replaceState so the back
 * button is not polluted by every tab / channel switch. No-ops if the
 * resulting hash matches what's already there (avoids redundant
 * history entries on noisy callers). */
export function writeHash(tab: string, params?: Record<string, string | null | undefined>): void {
  try {
    const next = "#" + formatHash(tab, params);
    if (window.location.hash === next) return;
    _suppressNext = true;
    const url =
      window.location.pathname + window.location.search + next;
    window.history.replaceState(window.history.state, "", url);
  } catch (_) {
    /* replaceState can throw on file:// or sandboxed contexts —
     * persistence is a nice-to-have, never fatal. */
    _suppressNext = false;
  }
}

/* Build a full absolute URL for the given state. Used by the
 * permalink / copy-link UI so the generated link is deep-linkable. */
export function buildPermalink(tab: string, params?: Record<string, string | null | undefined>): string {
  try {
    return (
      window.location.origin +
      window.location.pathname +
      "#" +
      formatHash(tab, params)
    );
  } catch (_) {
    return "#" + formatHash(tab, params);
  }
}

/* Register a handler for *external* hash changes (user paste / back
 * button / popstate). Suppresses the synthetic events our own
 * writeHash() triggers. Returns an unsubscribe function. */
export function onHashChange(handler: (state: HashState | null) => void): () => void {
  function listener() {
    if (_suppressNext) {
      _suppressNext = false;
      return;
    }
    try {
      handler(parseHash());
    } catch (_) {}
  }
  window.addEventListener("hashchange", listener);
  return function () {
    window.removeEventListener("hashchange", listener);
  };
}

/* Scroll a message into the chat feed viewport and highlight it,
 * plus a window of surrounding context rows (default 5) so the user
 * can read the thread around the link target. Returns true if the
 * message was found, false otherwise (caller decides whether to
 * retry after history fully loads). */
export function scrollMessageIntoView(
  msgId: string | number,
  opts?: { context?: number; highlightMs?: number },
): boolean {
  try {
    const id = String(msgId);
    const el = document.querySelector('[data-msg-id="' + id + '"]') as HTMLElement | null;
    if (!el) return false;
    const container = document.getElementById("messages");
    if (container) {
      const top = el.offsetTop - container.clientHeight / 2 + el.offsetHeight / 2;
      container.scrollTop = Math.max(0, top);
    } else {
      el.scrollIntoView({ block: "center", behavior: "smooth" });
    }
    /* Highlight target + N neighbours (spec: ~5 surrounding context
     * messages on scroll-to complete). */
    const context = Math.max(0, (opts && opts.context) || 5);
    const highlightMs = (opts && opts.highlightMs) || 2500;
    const targets: HTMLElement[] = [el];
    let prev = el.previousElementSibling as HTMLElement | null;
    let next = el.nextElementSibling as HTMLElement | null;
    const half = Math.floor(context / 2);
    for (let i = 0; i < half && prev; i++) {
      if (prev.classList && prev.hasAttribute("data-msg-id")) targets.push(prev);
      prev = prev.previousElementSibling as HTMLElement | null;
    }
    for (let i = 0; i < context - half && next; i++) {
      if (next.classList && next.hasAttribute("data-msg-id")) targets.push(next);
      next = next.nextElementSibling as HTMLElement | null;
    }
    targets.forEach((t) => t.classList.add("msg-highlight"));
    /* Strongest highlight on the direct target. */
    el.classList.add("msg-highlight-target");
    setTimeout(function () {
      targets.forEach((t) => t.classList.remove("msg-highlight"));
      el.classList.remove("msg-highlight-target");
    }, highlightMs);
    return true;
  } catch (_) {
    return false;
  }
}

/* Expose for inline handlers / cross-module consumers. */
(globalThis as any).__orochiUrlRouter = {
  parseHash,
  formatHash,
  writeHash,
  buildPermalink,
  onHashChange,
  scrollMessageIntoView,
};
